# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in bareruby.gemspec
gemspec

gem "irb"
gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "rubocop", "~> 1.21"

local_bareruby_compiler = File.expand_path("../bareruby-compiler", __dir__)
gem "bareruby-compiler", path: local_bareruby_compiler if Dir.exist?(local_bareruby_compiler)

lockfile false
